
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

@baseTheme = light
@background = #EE3C4B
@foreground = #e8e8e8
@accentColor = #FFD700
Component.arc = 12
Button.arc = 999

[style]Button.dashBut = \
    background: #d1244d; \
    foreground: #e8e8e8; \
    hoverBackground: #de2a55; \

[style]Button.mgrAdd = \
    background: #2bbf0d; \
    foreground: #e8e8e8; \
    borderColor: #2ea616; \
    borderWidth: 3; \
    arc: 24

[style]Button.mgrQS = \
    background: #c49d00; \
    foreground: #e8e8e8; \
    borderColor: #c9a516; \
    borderWidth: 3; \
    arc: 24

[style]Button.mgrDelS = \
    background: #FF2D08; \
    foreground: #e8e8e8; \
    borderColor: #c4361d; \
    borderWidth: 3; \
    arc: 24

# for tables
Table.background = #e8e8e8
Table.foreground = #0a0a0a

[style]Label.queueText = \
    foreground: #000000; \
    
[style]Panel.queuePanel = \
    background: #e8e8e8; \
    border: 10,10,10,10,#FFD666,3,24; \
    arc: 24 \

[style]Label.inqueueText = \
    foreground: #e8e8e8; \

[style]TextField.loginBar = \
    background: #e8e8e8; \
    foreground: #000000; \
    arc: 24 \

[style]PasswordField.loginBar = \
    background: #e8e8e8; \
    foreground: #000000; \
    arc: 24 \