# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

@baseTheme = light
@background = #056738
@foreground = #e8e8e8
@accentColor = #9A5621
Component.arc = 12
Button.arc = 25

[style]Button.dashBut = \
    background: #68d000; \
    foreground: #000000; \

[style]Button.mgrAdd = \
    background: #68d000; \
    foreground: #e8e8e8; \
    borderColor: #2ea616; \
    borderWidth: 3; \
    arc: 24

[style]Button.mgrQS = \
    background: #c49d00; \
    foreground: #e8e8e8; \
    borderColor: #c9a516; \
    borderWidth: 3; \
    arc: 24

[style]Button.mgrDelS = \
    background: #FF2D08; \
    foreground: #e8e8e8; \
    borderColor: #c4361d; \
    borderWidth: 3; \
    arc: 24

# for tables
Table.background = #e8e8e8
Table.foreground = #0a0a0a

[style]Label.queueText = \
    foreground: #000000; \
    
[style]Panel.queuePanel = \
    background: #e8e8e8; \
    border: 10,10,10,10,#9A5621,2.5,0; \
    arc: 0 \

[style]Label.inqueueText = \
    foreground: #e8e8e8; \

[style]TextField.loginBar = \
    background: #e8e8e8; \
    foreground: #000000; \
    border: 10,10,10,10,#9A5621,2,0; \
    arc: 0 \

[style]PasswordField.loginBar = \
    background: #e8e8e8; \
    foreground: #000000; \
    border: 10,10,10,10,#9A5621,2,0; \
    arc: 0 \